<a href="https://colab.research.google.com/github/Mithil-Katkoria/Day-1_ML/blob/main/Day_1_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**



In [11]:
import numpy as np
import os
import sys
import time

In [2]:
a = [1,2,3,4,5]
arr1 = np.array(a)

b = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(b)

print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2 3 4]
 [5 6 7 8]]


In [6]:
print(type(a))
print(type(b))

print(type(arr1))
print(type(arr2))

<class 'list'>
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [9]:
s = range(1000)
print("Size of each elements in the list in bytes",sys.getsizeof(s))
print("Complete list size in bytes",sys.getsizeof(s) * len(s))

Size of each elements in the list in bytes 48
Complete list size in bytes 48000


In [10]:
s = np.arange(1000)
print("Size of each elements in the list by bytes",s.itemsize)
print("Complete list size in bytes",s.size * s.itemsize)

Size of each elements in the list by bytes 8
Complete list size in bytes 8000


In [14]:
a = range(1000)
b = range(1000)

start = time.time()
end = time.time()

ab = [(a * b) for a,b in zip(a,b)]

print("Total time taken:",end - start)

Total time taken: 1.3828277587890625e-05


In [17]:
arr1 = np.arange(1000)
arr2 = np.arange(1000)

start = time.time()
end = time.time()

arr_mul = arr1 * arr2

print("Total time taken:",end - start)

Total time taken: 2.0265579223632812e-05


In [18]:
lst1 = [1,2,3,4]
arr = np.array(lst1)

print(arr)

[1 2 3 4]


In [19]:
print(arr + 1)

[2 3 4 5]


In [21]:
arr1 = np.array([[1,2,3,4], [5,6,7,8]],ndmin = 2)
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
arr2 = list(arr1)
print(arr2)

In [22]:
print(type(arr1),
      type(arr2))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
